---

- get_url:
    url: https://api.github.com/repos/grke/burp/releases/latest
    dest: /tmp/remote_version.txt
  when: VERSION == "latest"

- set_fact:
    remote_version: "{{ REMOTE_VERSION_RESPONSE.tag_name }}"
  when: VERSION == "latest"

- set_fact:
    remote_version: "{{ VERSION }}"
  when: VERSION != "latest"

- name: Determine installed burp version
  command: cat /.installed_version.txt
  register: installed_version
  ignore_errors: yes

- set_fact:
    update_available: true
  when: installed_version.stdout != remote_version
