---

# Determines if burp needs to be installed/updated

# determine the latest version
- get_url:
    url: https://api.github.com/repos/grke/burp/releases/latest
    dest: /tmp/remote_version.txt
  when: VERSION == "latest"

- command: echo "{{ REMOTE_VERSION_RESPONSE.tag_name }}"
  register: remote_version
  when: VERSION == "latest"

- name: Determine installed burp version
  command: cat /.installed_version.txt
  register: installed_version
  ignore_errors: yes

- set_fact:
    update_available: true
  when: installed_version.stdout != remote_version.stdout

- set_fact:
    update_available: false
  when: installed_version.stdout == remote_version.stdout
