---

APPLICATION_UID:     "{{ lookup('env', 'APPLICATION_UID') }}"
APPLICATION_GID:     "{{ lookup('env', 'APPLICATION_GID') }}"

VERSION:             "{{ lookup('env', 'VERSION') | lower | default('latest') }}"

REMOTE_VERSION_RESPONSE: "{{ lookup('file', '/tmp/version.txt') | from_json }}"

# Burp Cronjobs
ENABLE_CRON_DEDUP:   "{{ lookup('env', 'ENABLE_CRON_DEDUP') | default(True) }}"
ENABLE_CRON_SUMMARY: "{{ lookup('env', 'ENABLE_CRON_SUMMARY') | default(False) }}"
BURP_EMAIL:          "{{ lookup('env', 'BURP_EMAIL') }}"
